course/urls.py
from .views import *
from django.urls import path
from django.contrib import admin

urlpatterns = [
    # add tracking course
    path('add/', course_add_view, name='course_add'),
    path('load-courses/', ajax_load_courses, name='ajax_load_courses'),
    path('load-lectures/', ajax_load_lectures, name='ajax_load_lectures'),
    path('load-sections/', ajax_load_sections, name='ajax_load_sections'),

    # untrack a course
    path('untrack/', course_untrack_view, name='course_untrack'),
    path('untrack-sections/', ajax_untrack_sections, name='ajax_untrack_sections'),
]

course_monitor/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from course.views import *
from user.views import *
from .views import home_view

urlpatterns = [
    path('', home_view, name='home'),
    path('register/', user_register_view, name='register'),
    path('profile/', user_profile_view, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='user/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='user/logout.html'), name='logout'),
    path('emmmail/', email_list_view, name='email_list'),

    path('course/', include('course.urls')),
]

course/models.py
from django.db import models


class BaseModel(models.Model):
	objects = models.Manager()

	class Meta:
		abstract = True


class Subject(BaseModel):
	name = models.CharField(max_length=70)

	def __str__(self):
		return self.name  # this is what shows up in the admin page otherwise it would be "subject(1)"


class Course(BaseModel):
	subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
	abbrev = models.CharField(max_length=30)
	title = models.CharField(max_length=200)

	def __str__(self):
		return self.title

	class Meta:
		ordering = ['title']


class Lecture(BaseModel):
	course = models.ForeignKey(Course, on_delete=models.CASCADE)
	name = models.CharField(max_length=15)

	def __str__(self):
		return self.course.__getattribute__('abbrev') + ' ' + self.name

	class Meta:
		ordering = ['course', 'name']


class Section(BaseModel):
	lecture = models.ForeignKey(Lecture, on_delete=models.CASCADE)
	name = models.CharField(max_length=15)
	status = models.CharField(max_length=50, default='')
	num_spots_taken = models.CharField(max_length=100, default='')

	def __str__(self):
		return self.lecture.__str__() + ' ' + self.name + ' ' + self.status

	class Meta:
		ordering = ['lecture', 'name']


class Email(BaseModel):
	name = models.CharField(max_length=40)
	section = models.ManyToManyField(Section, blank=True, through='WhenToRemind')

	def __str__(self):
		return self.name


class WhenToRemind(BaseModel):
	email = models.ForeignKey(Email, on_delete=models.CASCADE)
	section = models.ForeignKey(Section, on_delete=models.CASCADE)
	only_remind_when_open = models.BooleanField(null=True)

course/forms.py
from django import forms

from course.models import Email, Course, Subject, Lecture, Section
from django.core.exceptions import ObjectDoesNotExist


class SectionForm(forms.Form):
    email = forms.EmailField()
    subject = forms.ModelChoiceField(queryset=Subject.objects.all().order_by('name'))
    course = forms.ModelChoiceField(queryset=Course.objects.all())
    lecture = forms.ModelChoiceField(queryset=Lecture.objects.all())
    section = forms.ModelMultipleChoiceField(queryset=Section.objects.all())
    only_remind_when_open = forms.BooleanField(label='Only remind me when it is "Open" '
                                                     '(i.e. don\'t remind me when it is "Waitlist").',
                                               required=False)

    def __init__(self, email_address='', *args, **kwargs):
        course_list = Course.objects.none()
        lecture_list = Lecture.objects.none()
        section_list = Section.objects.none()
        self.request = kwargs.pop('request', None)
        request = self.request
        if request is None:
            pass
        elif request.method == 'POST':
            subject_id = request.POST.get('subject')
            course_id = request.POST.get('course')
            lecture_id = request.POST.get('lecture')
            if subject_id != 'None':
                course_list = Course.objects.filter(subject=subject_id)
                if course_id != 'None':
                    lecture_list = Lecture.objects.filter(course=course_id)
                    if lecture_id != 'None':
                        section_list = Section.objects.filter(lecture=lecture_id)
        super().__init__(*args, **kwargs)
        self.fields['course'].queryset = course_list
        self.fields['lecture'].queryset = lecture_list
        self.fields['section'].queryset = section_list
        self.fields['email'] = forms.EmailField(initial=email_address)
        if email_address != '':
            self.fields['email'].widget.attrs['readonly'] = True


class SectionUntrackForm(forms.Form):
    email = forms.EmailField()
    section = forms.ModelMultipleChoiceField(queryset=Section.objects.all())

    def __init__(self, is_logged_in, email_address='', *args, **kwargs):
        if email_address != '':
            try:
                user = Email.objects.get(name=email_address)
            except ObjectDoesNotExist:
                section_list = Section.objects.none()
            else:
                section_list = user.section.all()
        else:
            section_list = Section.objects.none()
        super().__init__(*args, **kwargs)
        self.fields['section'].queryset = section_list
        if email_address != '':
            self.fields['email'] = forms.EmailField(initial=email_address)
        if is_logged_in:
            self.fields['email'].widget.attrs['readonly'] = True

course/views.py
from django.shortcuts import render
from django.contrib.admin.views.decorators import staff_member_required
from .forms import SectionForm, SectionUntrackForm
from .models import Email, Course, Lecture, Section, WhenToRemind
from django.core.exceptions import ObjectDoesNotExist


@staff_member_required(login_url='login')
def email_list_view(request):
	emails = Email.objects.all()
	return render(request, "course/email_list.html", {'emails': emails})


def course_detail_view(request):
	c = Course.objects.all().order_by()
	context = {
		'courses': c
	}
	return render(request, "course/course_detail.html", context)


def course_add_view(request):
	if request.user.is_authenticated:
		email_address = request.user.email
	else:
		email_address =''
	form = SectionForm(email_address=email_address)
	if request.method == 'POST':
		form = SectionForm(email_address, request.POST, request=request)
		if form.is_valid():
			email_address = request.POST.get('email')
			section_ids = request.POST.getlist('section')
			only_remind_when_open = request.POST.get('only_remind_when_open')
			if only_remind_when_open is None:
				only_remind_when_open = False
			else:
				only_remind_when_open = True
			email_query = Email.objects.filter(name=email_address)
			if email_query.count():
				email = Email.objects.filter(name=email_address)[0]
			else:
				email = Email.objects.create(name=email_address)
			for section_id in section_ids:
				section = Section.objects.get(id=section_id)
				email.section.add(section)
				WhenToRemind.objects.update_or_create(email=email, section=section,
													defaults={"only_remind_when_open": only_remind_when_open})
			form = SectionForm(email_address=email_address)

	context = {
		'form': form
	}
	return render(request, 'course/course_add.html', context)


def course_untrack_view(request):
	is_logged_in = request.user.is_authenticated
	if is_logged_in:
		email_address = request.user.email
	else:
		email_address = ''
	form = SectionUntrackForm(email_address=email_address, is_logged_in=is_logged_in)
	if request.method == 'POST':
		email_address = request.POST.get('email')
		form = SectionUntrackForm(is_logged_in, email_address, request.POST)
		if form.is_valid():
			email = Email.objects.get(name=email_address)
			section_ids = request.POST.getlist('section')
			for section_id in section_ids:
				section = Section.objects.get(id=section_id)
				email.section.remove(section)
			form = SectionUntrackForm(email_address=email_address, is_logged_in=is_logged_in)
		else:
			form = SectionUntrackForm(is_logged_in, email_address, request.POST)

	return render(request, 'course/course_untrack.html', {'form': form})


def ajax_load_courses(request):
	subject_id = request.GET.get('subject_pk')
	courses = Course.objects.filter(subject_id=subject_id).order_by('abbrev')
	return render(request, 'course/course_dropdown_list_options.html', {'courses': courses})


def ajax_load_lectures(request):
	course_id = request.GET.get('course_pk')
	lectures = Lecture.objects.filter(course_id=course_id).order_by('name')
	return render(request, 'course/lecture_dropdown_list_options.html', {'lectures': lectures})


def ajax_load_sections(request):
	lecture_id = request.GET.get('lecture_pk')
	sections = Section.objects.filter(lecture_id=lecture_id).order_by('name')
	return render(request, 'course/section_dropdown_list_options.html', {'sections': sections})


def ajax_untrack_sections(request):
	email = request.GET.get('email')
	try:
		user = Email.objects.get(name=email)
	except ObjectDoesNotExist:
		sections = Section.objects.none()
	else:
		sections = user.section.all()
	return render(request, 'course/section_dropdown_list_options.html', {'sections': sections})

course/templates/course/course_add.html
{% extends 'base.html' %}

{% block content %}
<h2>Add Reminder</h2>
<br>
<form method="post" id="addSectionForm" data-courses-url="{% url 'ajax_load_courses' %}"
data-lectures-url="{% url 'ajax_load_lectures' %}" data-sections-url="{% url 'ajax_load_sections' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" class="form-control btn btn-primary">
</form>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script>
        $("#id_subject").change(function () {
            var url = $("#addSectionForm").attr("data-courses-url"); // get the url of the `ajax_load_courses` view
            var subject_pk = $(this).val(); // get the selected subject ID from the HTML input

            $.ajax({                // initialize an AJAX request
                url: url,           // set the url of the request
                data: {
                    'subject_pk': subject_pk    // add the subject id to the GET parameter
                },
                success: function (data) {  // `data` is the return of the `ajax_load_courses` view function
                    $("#id_course").html(data);   // replace the contents of the course input with the data that came from the server
                }
            });
        });
        $("#id_course").change(function () {
            var url = $("#addSectionForm").attr("data-lectures-url"); // get the url of the `ajax_load_courses` view
            var course_pk = $(this).val(); // get the selected subject ID from the HTML input

            $.ajax({                // initialize an AJAX request
                url: url,           // set the url of the request
                data: {
                    'course_pk': course_pk    // add the subject id to the GET parameter
                },
                success: function (data) {  // `data` is the return of the `ajax_load_courses` view function
                    $("#id_lecture").html(data);   // replace the contents of the course input with the data that came from the server
                }
            });
        });
        $("#id_lecture").change(function () {
            var url = $("#addSectionForm").attr("data-sections-url");
            var lecture_pk = $(this).val(); // get the selected subject ID from the HTML input

            $.ajax({                // initialize an AJAX request
                url: url,           // set the url of the request
                data: {
                    'lecture_pk': lecture_pk    // add the subject id to the GET parameter
                },
                success: function (data) {  // `data` is the return of the `ajax_load_courses` view function
                    $("#id_section").html(data);   // replace the contents of the course input with the data that came from the server
                }
            });
        });
    </script>

{% endblock %}

course/templates/course/course_dropdown_list_options.html
<option value="" selected disabled hidden>
          Select a Course
</option>
{% for course in courses %}
    <option value="{{ course.pk }}">{{ course.title }}</option>
{% endfor %}

course/templates/course/course_untrack.html
{% extends 'base.html' %}

{% block content %}
<h2>Untrack a Class</h2>
<br>
<form method="post" id="untrackSectionForm" data-sections-url="{% url 'ajax_untrack_sections' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" class="form-control btn btn-primary">
</form>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script>
        $("#id_email").change(function () {
            var url = $("#untrackSectionForm").attr("data-sections-url");
            var email = $(this).val();

            $.ajax({                // initialize an AJAX request
                url: url,           // set the url of the request
                data: {
                    'email': email    // add the subject id to the GET parameter
                },
                success: function (data) {  // `data` is the return of the `ajax_load_courses` view function
                    $("#id_section").html(data);   // replace the contents of the course input with the data that came from the server
                }
            });
        });
    </script>

{% endblock %}

course/templates/course/email_list.html
{% extends 'base.html' %}

{% block content %}
<h1>Emails</h1>
<ul>
{% for email in emails %}
    <h3>{{ email.name }}</h3>
    {% for section in email.section.all.order_by %}
    <li>{{ section }}: {{ section.num_spots_taken }}</li>
    {% endfor %}
{% empty %}
    <li>No section yet.</li>
{% endfor %}
</ul>
{% endblock %}

course/templates/course/lecture_dropdown_list_options.html
<option value="none" selected disabled hidden>
          Select a Lecture
</option>
{% for lecture in lectures %}
    <option value="{{ lecture.pk }}">{{ lecture }}</option>
{% endfor %}

course/templates/course/section_dropdown_list_options.html
<option value="none" selected disabled hidden>
          Select a Section
</option>
{% for section in sections %}
    <option value="{{ section.pk }}">{{ section }}</option>
{% endfor %}